version: '3.8'
services:
  api:
    build: .
    image: fizz-buzz-api
    restart: always
    ports:
      - 8080:8080
  mongo:
    image: 'mongo:4.4'
    container_name: 'mongo'
    ports:
      - '27100:27017'