name: CICD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.7'
    
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: Run build
      run: go mod tidy && go mod vendor && go build . 
      
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    
    - name: Run testing
      run: go test ./...
    
    # Send slack notification
    - name: Send slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.

  deploy:
    runs-on: ubuntu-latest
    needs: [build] 
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} 
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: arthurbp/fizz-buzz-api
        tag_with_ref: true